name: Build, Test & Deploy

on:
  push:
    branches: [ main ]

jobs:
# название для Workflow
  build-and-test:
  # на какой операционной системе и какой версии будет выполняться рабочий процес
    runs-on: ubuntu-latest
     # шаги, которые будут выполнены в рамках задачи
    steps:
     # клонирует репозиторий в ранер, чтобы иметь доступ к исх.коду проекта 
      - name: Checkout code
        uses: actions/checkout@v4
    # устанавливет ноду
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    # устанавливет зависимоти
      - name: Install dependencies
        run: npm ci

    # собирает проект
      - name: Build project
        run: npm run build

    # запускаюи тесты
      - name: Run unit tests
        run: npm run test:unit

    # сохраняет папку dist результат сборки  как артефакт
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

# название для Workflow
  deploy:
  # зависимость от другой задачи необходимо чтобы сначала собрались тесты и собрался проект
    needs: build-and-test
    runs-on: ubuntu-latest
     # шаги, которые будут выполнены в рамках задачи
    steps:
    # скачивает артифакты чтобы получить результат из другой задачи
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
# поодключаемся к серверу по SSH и развертывает приложение
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            DEPLOY_PATH="/var/www/myapp"  # путь для деплоя 
            mkdir -p "$DEPLOY_PATH"  # создать папку если нет
            rm -rf "$DEPLOY_PATH"/* # ччистить старые файлы
            cp -r ./dist/* "$DEPLOY_PATH"/  # скопировать новые файлы
            echo "✅"  # если все ок то ок
